### ISSUE TITLE
Panic: Bundle not found after receiving a milestone

### ISSUE THREAD

**Issue by viossat** [iotaledger/hornet#444] opened 2020-05-21 14:11 UTC
Version: 0.4-RC9

```
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 80396/80396, TPS (in/new/out): 00072/00015/00023 
INFO	Tangle	tangle/milestones.go:30	Valid milestone detected! Index: 80397, Hash: RBAXLYZSDGOYJQUGFVEKT9JVMEZTMPNMZBOMPHY9TGJRZOMVSTQKEGGYWQEDODIQ9UESNTQBPOEVZA999 
INFO	Tangle	tangle/solidifier.go:344	Run solidity check for Milestone (80397)... 
INFO	Tangle	tangle/solidifier.go:266	Solidifier finished: txs: 2, collect: 0s, total: 0s 
PANIC	Tangle	tangle/confirmation.go:99	confirmMilestone: Tx: LW9YMYDMFOIQYVDVZEQ9HMXIIBPMKYCYMKSKUSXAFCIAN9MSZVZHDEYDCMA9SZFWOKVPOKYDAZFRJC999, Bundle not found: PCTKGCOWHSBPMUQEQAIVGOBUYCMCXGSHRQOQKGZOMJAE9YBSVYUQYWS9SJRMPGQWCSUOWBDGIXXNUSOOC 
github.com/gohornet/hornet/plugins/tangle.confirmMilestone 
	/src/plugins/tangle/confirmation.go:99 
github.com/gohornet/hornet/plugins/tangle.solidifyMilestone 
	/src/plugins/tangle/solidifier.go:376 
github.com/gohornet/hornet/plugins/tangle.configureTangleProcessor.func3 
	/src/plugins/tangle/tangle_processor.go:51 
github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1 
	/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200518225146-500916854cb2/workerpool/workerpool.go:158 
panic: confirmMilestone: Tx: LW9YMYDMFOIQYVDVZEQ9HMXIIBPMKYCYMKSKUSXAFCIAN9MSZVZHDEYDCMA9SZFWOKVPOKYDAZFRJC999, Bundle not found: PCTKGCOWHSBPMUQEQAIVGOBUYCMCXGSHRQOQKGZOMJAE9YBSVYUQYWS9SJRMPGQWCSUOWBDGIXXNUSOOC 
```

After restart it is stuck at `INFO Tangle tangle/revalidation.go:128 analyzed 4250000 transactions`

**Comment by alexsporn** [comment] 2020-05-21 14:25
Duplicate of #437

**Closed as completed by alexsporn** 2020-05-21 14:25 UTC
Labels: bug
