### ISSUE TITLE
High disc usage for no apparent reason

### ISSUE THREAD

**Issue by Travetown** [iotaledger/hornet#914] opened 2021-03-01 08:20 UTC
The node suddenly has a high disc usage. It is not clear to me when or why this happened.
The dashboard shows that the database size fluctuates between 15 and 25 GB within a few minutes.
Pruning and spamming are not active.

**To Reproduce**
No idea

**Environment information:**
 Ubuntu 20.04
 Hetzner CPX31 (Hornet only) 
"engine": "pebble",

Hornet Build 1d5576e

Stack-Dump: https://ybin.me/p/8175554e19c667e4#gTF5smDiVV8reekd7gtV1Ie0Jw9KE4E16uKw8FY2zuk=
[memory_profile.pdf](https://github.com/gohornet/hornet/files/6060026/memory_profile.pdf)
<img width="682" alt="Bildschirmfoto 2021-03-01 um 08 22 20" src="https://user-images.githubusercontent.com/66588710/109470024-22e00f80-7a6f-11eb-8780-ff41b3988449.png">

**Comment by muXxer** [comment] 2021-03-01 08:28
Is it still ongoing? Do you have logs about current incoming MPS?

**Comment by Travetown** [comment] 2021-03-01 08:37
I restarted the node. Now the problem is gone. But here are the last hours before the restart.


[hornet_log.zip](https://github.com/gohornet/hornet/files/6060163/hornet_log.zip)

**Comment by muXxer** [comment] 2021-03-01 08:42
Is it normal that you have around 200 new "in" messages? Or is that gone after the restart?

**Comment by Travetown** [comment] 2021-03-01 08:47
10 neighbours 🥴

**Comment by Travetown** [comment] 2021-03-01 08:48
Can't say "no"
Before that, I always had so many neighbors and the problem never occurred

**Comment by Travetown** [comment] 2021-03-06 12:55
It happend again (Build: 566307d) No spamming, no pruning. After about a day without having done anything with the node.

<img width="1118" alt="Bildschirmfoto 2021-03-06 um 13 50 46" src="https://user-images.githubusercontent.com/66588710/110207405-94f79080-7e83-11eb-9d17-5530555ac9a4.png">

**Comment by muXxer** [comment] 2021-03-06 12:59
Could you do a CPU Profile with pprof in the moment it happens?

**Comment by muXxer** [comment] 2021-03-06 13:00
How to take a CPU profile

First install go and the necesarry lib  (must be done on the HORNET node)
`sudo apt install graphviz`

Take a CPU Profile (must be done on the HORNET node):
`go tool pprof --pdf http://localhost:6060/debug/pprof/profile?seconds=30 > cpu_profile.pdf`

**Comment by Travetown** [comment] 2021-03-06 13:04
okay I will if it happens again.

DB-Size Last 2 hours 

![image](https://user-images.githubusercontent.com/66588710/110207591-d89eca00-7e84-11eb-9322-e26accca511c.jpeg)

**Comment by muXxer** [comment] 2021-03-06 13:05
The DB engine (pebble) is running the compaction.

**Comment by Travetown** [comment] 2021-03-06 14:42
Happend again.
graphviz is already the newest version (2.42.2-3build2). 

root@Chrysalis:~# go tool pprof --pdf http://localhost:6060/debug/pprof/profile?seconds=30 > cpu_profile.pdf
....
Fetching profile over HTTP from http://localhost:6060/debug/pprof/profile?seconds=30
Saved profile in /root/pprof/pprof.hornet.samples.cpu.001.pb.gz


But this is (unpacked) not a PDF. Is the command correct?

[pprof.hornet.samples.cpu.001.pb.gz](https://github.com/gohornet/hornet/files/6095507/pprof.hornet.samples.cpu.001.pb.gz)

**Comment by muXxer** [comment] 2021-03-06 14:43
there is a pdf in the folder you called that command, I'm sure ;)

**Comment by Travetown** [comment] 2021-03-06 14:45
ups 


[cpu_profile.pdf](https://github.com/gohornet/hornet/files/6095520/cpu_profile.pdf)

**Comment by muXxer** [comment] 2021-03-06 14:47
Yeah as I thought, its the compaction of the database.
This is something which is triggered by the DB engine itself. It should calm done after it finished.
How long does this process take?
It's not a "bug" from our side, but intended behavior by the db.

**Comment by Travetown** [comment] 2021-03-06 14:48
When I first reported it, it had been going on for about 4 hours.
Now one hour:

<img width="1383" alt="Bildschirmfoto 2021-03-06 um 15 52 09" src="https://user-images.githubusercontent.com/66588710/110210864-ef98e880-7e93-11eb-89c8-08c35122622c.png">


<img width="1402" alt="Bildschirmfoto 2021-03-06 um 15 49 49" src="https://user-images.githubusercontent.com/66588710/110210798-a5176c00-7e93-11eb-9454-f2feaa21080c.png">

So far it has always occurred with a DB size of around 15-20 GB.

**Comment by muXxer** [comment] 2021-03-28 19:49
Fixed with #974

**Closed as completed by muXxer** 2021-03-28 19:49 UTC
Labels: bug
