### ISSUE TITLE
Merkle Tree Generation fails [243rd trit must be zero]

### ISSUE THREAD

**Issue by Fredi100** [iotaledger/hornet#805] opened 2020-12-30 17:07 UTC
**Describe the bug**
When trying to generate a new Merkle Tree for a private tangle, a panic error gets thrown and the tool exists.
```
calculating 1048576 addresses...
panic: each 243rd trit must be zero: invalid trit

goroutine 83 [running]:
github.com/iotaledger/iota.go/merkle.calculateAllAddresses.func1(0xc00003c990, 0xc00009e1e0, 0xc00003a009, 0x51, 0x2, 0xc000680000, 0x100000, 0x100000)
        /github/home/go/pkg/mod/github.com/iotaledger/iota.go@v1.0.0-beta.15.0.20201113171647-14f7a0d87712/merkle/merkle_tree.go:110 +0x14d
created by github.com/iotaledger/iota.go/merkle.calculateAllAddresses
        /github/home/go/pkg/mod/github.com/iotaledger/iota.go@v1.0.0-beta.15.0.20201113171647-14f7a0d87712/merkle/merkle_tree.go:104 +0x1ab
```

**To Reproduce**
- Start with a fresh installation of hornet.
- Follow the instructions for a private tangle.
- Try to generate a merkle tree.

**Expected behavior**
The tool should generate a merkle tree.

**Environment information:**
 - OS: Ubuntu 20.04 LTS
 - RAM: 2 GB
 - Cores: 8
 - Type: VPS
 - HORNET version 0.5.6

**Additional context**
Apparently this error was already fixed in HORNET itself, but was missed in the merkle tree tool

**Comment by muXxer** [comment] 2020-12-30 17:08
Replace the last Tryte of your Coordinator Seed with a "9".
We won't fix this, since its not a bug. It could fail earlier, but Merkle trees for COO will be removed with chrysalis anyway.

**Closed as completed by muXxer** 2020-12-30 17:08 UTC
Labels: bug
